RoadPolice/Controllers/CommonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RoadPolice.Models;
using RoadPolice.Services;

namespace RoadPolice.Controllers
{
    public class CommonController : Controller
    {
        // GET: Common
        public ActionResult Menu()
        {
            var service = new UserService();
            var model = new MenuViewModel();
            if (!User.Identity.IsAuthenticated)
                return PartialView(model);
            model.IsAdmin = service.IsUserAdmin(User.Identity.Name);
            model.IsDriver = service.IsUserDriver(User.Identity.Name);
            model.IsInspector = service.IsUserInspector(User.Identity.Name);
            return PartialView(model);
        }

    }
}

RoadPolice/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>@ViewBag.Title - ГИБДД ПМР</title>
    <!-- Favicon-->
    <link rel="icon" href="favicon.ico" type="image/x-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">

    @Styles.Render("~/Content/theme")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>

<body class="theme-blue-grey">
<div class="page-loader-wrapper">
    <div class="loader">
        <div class="preloader">
            <div class="spinner-layer pl-red">
                <div class="circle-clipper left">
                    <div class="circle"></div>
                </div>
                <div class="circle-clipper right">
                    <div class="circle"></div>
                </div>
            </div>
        </div>
        <p>Пожалуйста подождите...</p>
    </div>
</div>
<div class="overlay"></div>
<nav class="navbar">
    <div class="container-fluid">
        <div class="navbar-header">
            <a href="javascript:void(0);" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false"></a>
            <a href="javascript:void(0);" class="bars"></a>
            @(Request.IsAuthenticated ? Html.ActionLink("ГИБДД ПМР", "Index", "Home", new {area = ""}, new {@class = "navbar-brand"}) : Html.ActionLink("ГИБДД ПМР", "Login", "Account", new {area = ""}, new {@class = "navbar-brand"}))
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse">
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</nav>
<section>
    <aside id="leftsidebar" class="sidebar">
        <div class="menu">
            <ul class="list">
                @*<li class="header">MAIN NAVIGATION</li>*@
                @Html.Action("Menu","Common")
            </ul>
        </div>
        <div class="legal">
            <div class="copyright">
                &copy; @DateTime.Now.Year - <a href="javascript:void(0);">ГИБДД ПМР</a>.
            </div>
        </div>
    </aside>
</section>

<section class="content">
    <div class="container-fluid">
        @RenderBody()
    </div>
</section>

<!-- Jquery Core Js -->
<script src="~/Content/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap Core Js -->
<script src="~/Content/plugins/bootstrap/js/bootstrap.js"></script>
<!-- Select Plugin Js -->
<script src="~/Content/plugins/bootstrap-select/js/bootstrap-select.js"></script>
<!-- Slimscroll Plugin Js -->
<script src="~/Content/plugins/jquery-slimscroll/jquery.slimscroll.js"></script>
<!-- Waves Effect Plugin Js -->
<script src="~/Content/plugins/node-waves/waves.js"></script>
<!-- Custom Js -->
<script src="~/Scripts/js/admin.js"></script>

@* @Scripts.Render("~/bundles/jquery") *@
@* @Scripts.Render("~/bundles/bootstrap") *@
@RenderSection("scripts", false)
</body>

</html>