RoadPolice/Controllers/ProtocolsStatisticController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using RoadPolice.Models;

namespace RoadPolice.Controllers
{
    public class ProtocolsStatisticController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ProtocolsStatistic
        public ActionResult Index(string type, string startDate, string endDate)
        {

            DateTime baselineDate = getBaseDate(type);

            ViewBag.DateType = type;


            //            var arr =  db.PoliceProtocols.Where(a => a.Id > 0)
            //                         .GroupBy(a => a.Fine)
            //                         .Select(x => new { x.Key,
            //                             x.Key.Title,
            //                             Count = x.Count() });

            var protocolStatistics = db.PoliceProtocols.Where(a => a.FineDate > baselineDate)
                         .GroupBy(a => a.Fine)
                         .Select(x => new ProtocolStatistic
                         {
                             Title = x.Key.Title,
                             Count = x.Count()
                         });


            if (startDate != null && endDate != null)
            {

                var sDate = Convert.ToDateTime(startDate);
                var eDate = Convert.ToDateTime(endDate);

                ViewBag.sDate = startDate;
                ViewBag.eDate = endDate;

               protocolStatistics = db.PoliceProtocols.Where(a => a.FineDate >= sDate && a.FineDate <= eDate)
                        .GroupBy(a => a.Fine)
                        .Select(x => new ProtocolStatistic
                        {
                            Title = x.Key.Title,
                            Count = x.Count()
                        });

            }

            return View(protocolStatistics.ToList());
        }

        public ActionResult GetChart(string type, string startDate, string endDate, int chartTypeCode)
        {

            var baseDate = getBaseDate(type);

            string chartType = chartTypeCode == 0 ? "column" : "pie";

            var protocolStatistics = db.PoliceProtocols.Where(a => a.FineDate > baseDate)
                       .GroupBy(a => a.Fine)
                       .Select(x => new ProtocolStatistic
                       {
                           Title = x.Key.Title,
                           Count = x.Count()
                       });

            if (startDate != null && endDate != null)
            {

                var sDate = Convert.ToDateTime(startDate);
                var eDate = Convert.ToDateTime(endDate);


                protocolStatistics = db.PoliceProtocols.Where(a => a.FineDate >= sDate && a.FineDate <= eDate)
                         .GroupBy(a => a.Fine)
                         .Select(x => new ProtocolStatistic
                         {
                             Title = x.Key.Title,
                             Count = x.Count()
                         });

            }

            var xValues = new ArrayList();
            var yValues = new ArrayList();

            foreach (var item in protocolStatistics)
            {
                xValues.Add(item.Title);
                yValues.Add(item.Count);
            }


//            new Chart(width: 800, height: 500, theme: ChartTheme.Blue)
            new Chart(width: 800, height: 500)
                .AddTitle("Статистика правонарушений:")
                .AddLegend()
                .AddSeries("default", chartType: chartType, xValue: xValues, yValues: yValues)
                .Write("bmp");

            return null;
        }


        private DateTime getBaseDate(string type)
        {
            DateTime baselineDate;



            switch (type)
            {
                case "week":
                    baselineDate = DateTime.Today.AddDays(-7);
                    break;
                case "month":
                    baselineDate = DateTime.Today.AddMonths(-1);
                    break;

                case "year":
                    baselineDate = DateTime.Today.AddMonths(-12);
                    break;

                default:
                    baselineDate = DateTime.Today.AddMonths(-999);
                    break;
            }

            return baselineDate;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RoadPolice/Views/ProtocolsStatistic/Details.cshtml
@model RoadPolice.Models.PoliceProtocol

@{
    ViewBag.Title = "Подробности";
}

<h2>Подробности</h2>

<div>
    <h4>Протокол</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Driver.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Driver.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fine.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fine.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PoliceInspector.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PoliceInspector.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FineDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FineDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vehicle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vehicle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VehicleNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VehicleNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsPaid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsPaid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PaidDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaidDate)
        </dd>

    </dl>
</div>
<p>
@*    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |*@
    @Html.ActionLink("Назад", "Index")
</p>

RoadPolice/Views/ProtocolsStatistic/Index.cshtml
@model IEnumerable<RoadPolice.Models.ProtocolStatistic>  

@{
    ViewBag.Title = "Статистика";
}

<div style="width: 900px; margin: 0 auto;">
    <h2>Статистика правонарушений</h2>
    
    <div style="margin-top: 20px;">
        @Html.ActionLink("За неделю", "Index", new { type = "week"}, new { @class = "btn btn-default" })
        @Html.ActionLink("За месяц", "Index", new { type = "month" }, new { @class = "btn btn-default" })
        @Html.ActionLink("За год", "Index", new { type = "year" }, new { @class = "btn btn-default" })
    </div>
    
    <hr/>
   
    <div style="margin-top: 20px;">
        <h3>Фильтр по дате:</h3>
        @using (Html.BeginForm("Index", "ProtocolsStatistic", FormMethod.Get, new {Id = "Form1"}))
        {
            <div class="form-group">
                <label class="control-label">Начало</label>
                <input class="form-control datefield" type="date" name="startDate" required/>
            </div>

            <div class="form-group">
                <label class="control-label">Конец</label>
                <input class="form-control datefield" type="date" name="endDate" required/>
            </div>

            <div class="form-group">
                <input type="submit" value="Поиск" class="btn btn-default"/>
            </div>

        }
    </div>
   
    <hr/>
    <div style="margin-top: 20px;">
        
        <h3>Штрафы:</h3><br/>

        @{
            int x = 0;
        }

        @foreach (var item in Model)
        {
            <strong>
                <p>@item.Title - @item.Count</p></strong>
            x += @item.Count;
        }

        @if (x > 0)
        {
            <br/><strong><p>Итого: @x</p></strong>
        }
        else
        {
            <strong><p>За выбранный период штрафов нет!</p></strong>
        }

    </div>
    
    <hr/>
    
    @*<img style="margin-top: 25px;" src="@Url.Action("GetChart", new {type = @ViewBag.DateType, chartTypeCode = 1})" alt="Statistic Chart" />*@

    <img style="margin-top: 25px;" src="@Url.Action("GetChart", new {type = @ViewBag.DateType, startDate = @ViewBag.sDate, endDate = @ViewBag.eDate,chartTypeCode = 0})" alt="Statistic Chart"/>
    

</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @*@RenderSection("scripts", required: false)*@

    <script type="text/javascript">
        //alert('test');



        function showProtocols() {
            var licenceNumber = $('#licenceNumber').val();
            //alert(licenceNumber);
            window.open("/DriverProtocols/Details/" + licenceNumber,
                "_blank");
        }

    </script>
}

RoadPolice/Views/ProtocolsStatistic/Index_.cshtml
@model IEnumerable<RoadPolice.Models.ProtocolStatistic>  

@{
    ViewBag.Title = "Статистика";
}

@{
//    string[] titles = {};
//    int[] counts= {};

    var titles = new List<String>();
    var vaules = new List<String>();


    foreach (var item in Model)
    {
        titles.Add(item.Title);
        vaules.Add(item.Count.ToString());
        <p>@item.Title</p>
    }
}

@*@{
    var myChart = new Chart(width: 1024, height: 400)
       .AddTitle("Отчет по штрафам")
       .AddSeries(chartType: "column",
          xValue: new[] { "Остановка стоянка", "Превышение скорости", "Julie", "Mary", "Dave" },
          yValues: new[] { "16", "6", "4", "5", "3" })
       .Write();
}*@

@*@{
    var myChart = new Chart(width: 1024, height: 400)
       .AddTitle("Отчет по штрафам")
       .AddSeries(chartType: "column",
          xValue: titles,
          yValues: vaules)
       .Write();
}*@


<div style="min-height: 450px;  margin: 0 auto;">
    <h2>Просмотр статистики правонарушений</h2>
    
    @foreach (var item in Model)
    {
        <p>@item.Title</p>
    }
    
    <img src="@Url.Action("GetChart")" alt="Statistic Chart"/>
    

    <form action="javascript:showProtocols()">

        <div class="form-group">


            <div class="col-md-10">
                <input type="search" placeholder="Номер удостоверения" class="form-control" id="licenceNumber">
            </div>

        </div>

        <div class="form-group">
            <div class="col-md-10">
                <input type="submit" style="margin-top: 8px;" value="Поиск" class="btn btn-default" />
            </div>
        </div>


    </form>

</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @*@RenderSection("scripts", required: false)*@

    <script type="text/javascript">
        //alert('test');



        function showProtocols() {
            var licenceNumber = $('#licenceNumber').val();
            //alert(licenceNumber);
            window.open("/DriverProtocols/Details/" + licenceNumber,
                "_blank");
        }

    </script>
}